version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - BINANCE_API_KEY=$BINANCE_API_KEY
            - BINANCE_API_SECRET=$BINANCE_API_SECRET
            - TRADEAI_DB_NAME=$TRADEAI_DB_NAME
            - TRADEAI_DB_USER_NAME=$TRADEAI_DB_USER_NAME
            - TRADEAI_DB_USER_PASSWORD=$TRADEAI_DB_USER_PASSWORD
            - TRADEAI_DB_HOST=$TRADEAI_DB_HOST
            - TRADEAI_DB_PORT=$TRADEAI_DB_PORT
            - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A trade_ai worker --autoscale=10,3 -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
            - TRADEAI_DB_NAME=$TRADEAI_DB_NAME
            - TRADEAI_DB_USER_NAME=$TRADEAI_DB_USER_NAME
            - TRADEAI_DB_USER_PASSWORD=$TRADEAI_DB_USER_PASSWORD
            - TRADEAI_DB_HOST=$TRADEAI_DB_HOST
            - TRADEAI_DB_PORT=$TRADEAI_DB_PORT
            - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=$TRADEAI_DB_NAME
            - POSTGRES_USER=$TRADEAI_DB_USER_NAME
            - POSTGRES_PASSWORD=$TRADEAI_DB_USER_PASSWORD
        volumes:
            - pgdata:/var/lib/postgresql/data/
    redis:
        image: "redis:alpine"

volumes:
    pgdata:
